name: $(Date:yyyy).$(Month).$(DayOfMonth).$(rev:r)
pool:
  vmImage: windows-2019
steps:
  - script: nuget restore FluentHttpClient.sln    
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Restore

  - script: dotnet build --configuration Release
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Build
  
  - script: dotnet test --logger trx
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Test

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '$(Build.SourcesDirectory)/**/*.trx'      

  - task: DotNetCoreCLI@2
    displayName: Create Package
    inputs:
      command: pack
      packagesToPack: '$(Build.SourcesDirectory)/src/CSharpsi.FluentHttpClient/CSharpsi.FluentHttpClient.csproj'
      packDirectory: '$(Build.ArtifactStagingDirectory)/package'
      versioningScheme: byBuildNumber
    timeoutInMinutes: 30

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/package'
      artifactName: package
